### ISSUE TITLE
Add contact links to meet-pages

### ISSUE THREAD

**Issue by emmellsoft** [LivingIT/livingit.se#19]
We need to have the possibility to have links to various social platforms on our personal pages, like LinkedIn, Twitter, Facebook etc.

**Comment by frippz** [comment]
@emmellsoft Can you give me a comprehensive list of the platforms we should support (mostly for the icons)?

**Comment by emmellsoft** [comment]
@frippz let's start with LinkedIn, Twitter, Facebook and GitHub
